const foodData = require("../../static/data.js");
/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("foods").del();
  await knex("foods").insert([
    {
      name: "Spicy seasoned seafood noodles",
      category_id: 1,
      price: "2.29",
      images: "image1.png",
      bowls: 20,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Salted Pasta with mushroom sauce",
      category_id: 1,
      price: "2.69",
      images: "image2.png",
      bowls: 11,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Beef dumpling in hot and sour soup",
      category_id: 1,
      price: "2.99",
      images: "image3.png",
      bowls: 16,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Healthy noodle with spinach leaf",
      category_id: 1,
      price: "3.29",
      images: "image4.png",
      bowls: 22,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Hot spicy fried rice with omelet",
      category_id: 1,
      price: "3.49",
      images: "image5.png",
      bowls: 13,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Spicy instant noodle with special omelette",
      category_id: 1,
      price: "3.59",
      images: "image6.png",
      bowls: 17,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Parmesan Spinach Mushroom Pasta Skillet",
      category_id: 1,
      price: "4.25",
      images: "Food7.jfif",
      bowls: 20,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Garlic Mushrooms",
      category_id: 1,
      price: "5.60",
      images: "Food8.jfif",
      bowls: 12,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Baked Honey Cilantro Lime Salmon",
      category_id: 1,
      price: "10.30",
      images: "Food9.jpg",
      bowls: 5,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Bowtie Chicken Caesar Salad - The Girl Who Ate Everything",
      category_id: 2,
      price: "5.9",
      images: "Cold1.jfif",
      bowls: 10,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Veggie burrito bowls wihgrilled mango",
      category_id: 2,
      price: "5.1",
      images: "Cold2.png",
      bowls: 15,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Skinny Chicken Salad",
      category_id: 2,
      price: "2.95",
      images: "Cold3.jfif",
      bowls: 5,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Whole Wheat Pita with Kale and Asiago",
      category_id: 2,
      price: "5.29",
      images: "Cold4.jfif",
      bowls: 14,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Crab Salad",
      category_id: 2,
      price: "11.15",
      images: "Cold5.jfif",
      bowls: 16,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Greek Chicken Roll Salad",
      category_id: 2,
      price: "4.2",
      images: "Cold6.jfif",
      bowls: 50,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Watermelon and Feta Salad",
      category_id: 2,
      price: "4.14",
      images: "Cold7.1.jfif",
      bowls: 27,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Caesar Gazpacho",
      category_id: 2,
      price: "13.29",
      images: "Cold8.jfif",
      bowls: 12,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Apple and Blue Cheese on Endive",
      category_id: 2,
      price: "14.18",
      images: "Cold9.jfif",
      bowls: 17,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Cheesy Potato Soup",
      category_id: 3,
      price: "4.21",
      images: "Soup1.jfif",
      bowls: 14,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Slow Cooker Chicken and Potato Soup",
      category_id: 3,
      price: "4.23",
      images: "Soup2.jfif",
      bowls: 27,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Onion, Kale, Chickpea, and Chicken Soup",
      category_id: 3,
      price: "7.14",
      images: "Soup3.png",
      bowls: 7,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Soulful Chicken Soup",
      category_id: 3,
      price: "6.13",
      images: "Soup4.jfif",
      bowls: 11,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Chicken and Cornbread Dumplings",
      category_id: 3,
      price: "9.49",
      images: "Soup5.jfif",
      bowls: 7,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Slow Cooker Chicken Chili",
      category_id: 3,
      price: "2.14",
      images: "Soup6.jfif",
      bowls: 17,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Creamy Leek and Parsnip Soup",
      category_id: 3,
      price: "3.78",
      images: "Soup7.jfif",
      bowls: 13,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Smoky Ham and Split Pea Soup",
      category_id: 3,
      price: "5.45",
      images: "Soup8.jfif",
      bowls: 6,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Black Garlic and Lentil Soup",
      category_id: 3,
      price: "6.47",
      images: "Soup9.jfif",
      bowls: 19,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "New York Strip",
      category_id: 4,
      price: "20.50",
      images: "Grill1.jfif",
      bowls: 5,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Ribye",
      category_id: 4,
      price: "19.80",
      images: "Grill2.jfif",
      bowls: 2,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Veal",
      category_id: 4,
      price: "19.30",
      images: "Grill3.1.jfif",
      bowls: 7,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Pork Chops",
      category_id: 4,
      price: "15.70",
      images: "Grill4.jfif",
      bowls: 4,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Baby ribs and shrip",
      category_id: 4,
      price: "18.00",
      images: "Grill5.jfif",
      bowls: 14,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Salmon fillet",
      category_id: 4,
      price: "17.40",
      images: "Grill6.jfif",
      bowls: 3,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Tuna Steak",
      category_id: 4,
      price: "24.00",
      images: "Grill7.jfif",
      bowls: 2,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Country-Style Ribs with Quick-Pickled Watermelon",
      category_id: 4,
      price: "30.25",
      images: "Grill8.jpg",
      bowls: 5,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Grilled Kielbasa Tacos",
      category_id: 4,
      price: "27.90",
      images: "Grill9.jfif",
      bowls: 1,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "The Only Salsa You Need",
      category_id: 5,
      price: "5.00",
      images: "Appetizer1.jpg",
      bowls: 14,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Curried Peanut Dip",
      category_id: 5,
      price: "3.00",
      images: "Appetizer2.jpg",
      bowls: 2,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Giardiniera Antipasto Platter",
      category_id: 5,
      price: "3.47",
      images: "Appetizer3.jpg",
      bowls: 4,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Mala Fried Peanuts",
      category_id: 5,
      price: "3.20",
      images: "Appetizer4.jpg",
      bowls: 37,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Relish Tray with D.I.Y. Eggs",
      category_id: 5,
      price: "2.15",
      images: "Appetizer5.jpg",
      bowls: 26,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Crispy Cheese Twists",
      category_id: 5,
      price: "3.78",
      images: "Appetizer6.jpg",
      bowls: 14,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Spinach and Feta Tarte Soleil",
      category_id: 5,
      price: "7.94",
      images: "Appetizer7.jpg",
      bowls: 16,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Ham and Cheese Feuillete",
      category_id: 5,
      price: "4.41",
      images: "Appetizer8.jpg",
      bowls: 7,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Cashew Nam Prik",
      category_id: 5,
      price: "1.98",
      images: "Appetizer9.jpg",
      bowls: 42,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Mixed berry mousse",
      category_id: 6,
      price: "7.90",
      images: "Dessert1.jfif",
      bowls: 7,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Mango and coconut souffle",
      category_id: 6,
      price: "3.45",
      images: "Dessert2.jfif",
      bowls: 17,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Homemade carrot cake",
      category_id: 6,
      price: "14.00",
      images: "Dessert3.jfif",
      bowls: 19,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Matcha cake",
      category_id: 6,
      price: "25.60",
      images: "Dessert4.jfif",
      bowls: 3,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Vegan chocolate cake",
      category_id: 6,
      price: "8.45",
      images: "Dessert5.jfif",
      bowls: 15,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Praline and ganache cake",
      category_id: 6,
      price: "11.60",
      images: "Dessert6.jfif",
      bowls: 7,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Blondie with vanilla ice cream",
      category_id: 6,
      price: "5.50",
      images: "Dessert7.jfif",
      bowls: 6,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "Re-invented cheesecake",
      category_id: 6,
      price: "17.50",
      images: "Dessert8.jfif",
      bowls: 10,
      total_sold: 0,
      is_deleted: false,
    },
    {
      name: "XL lemon meringue pie",
      category_id: 6,
      price: "9.47",
      images: "Dessert9.jfif",
      bowls: 9,
      total_sold: 0,
      is_deleted: false,
    },
  ]);
};
